services:
  - type: web
    name: medical-insurance-cost-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROK_MODEL
        value: llama-3.1-8b-instant
      - key: XAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
